import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import { getMarkdownData } from "../../../lib/getMarkdownData";
import ReactMarkdown from "react-markdown";

export async function getStaticProps() {
  const orderCloudData = await getMarkdownData("orderCloud.md", 'product/commerce');
  const sitecoreCommerceData = await getMarkdownData("sitecoreCommerce.md", 'product/commerce');

  return {
    props: {
      orderCloudData,
      sitecoreCommerceData
    },
  };
}

export default function Commerce({ orderCloudData, sitecoreCommerceData }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Commerce 💸
        </h1>
        <div className={styles.grid}>

          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{orderCloudData.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{sitecoreCommerceData.markdown}</ReactMarkdown>
          </div>


          <div className={styles.socialsCard}>
            <h2>General Commerce Socials</h2>
          </div> 
          <div className={styles.socialsCard}>
            <h2>News & Announcements</h2>
            <a href="" className={styles.link}><li>Cool new commerce things</li></a>
          </div>
        </div>
      </main>
    </div>)
}

