import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Footer from '../../components/footer'
import ProductCard from '../../components/productCard'


export default function Commerce() {

  const { OrderCloudDocLinks, OrderCloudDiscoverLinks, OrderCloudLearnLinks, OrderCloudPlaygroundLinks } = OrderCloudLinks()
  const { SitecoreCommerceDocLinks, SitecoreCommerceDiscoverLinks, SitecoreCommerceLearnLinks, SitecoreCommercePlaygroundLinks } = SitecoreCommerceLinks()

  return (
    <div className={styles.container}>
      <Head>
        <title>Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Commerce 💸
        </h1>
        <a href="/" className={styles.link}><h2>Take me Home</h2></a>
        <div className={styles.grid}>
          <div className={styles.searchCard}>
            <h2>I'm a unified search 🔍</h2>
          </div>
          <ProductCard
            productName="Four51 (OrderCloud)"
            productLink=""
            DocLinks={OrderCloudDocLinks}
            DiscoverLinks={OrderCloudDiscoverLinks}
            LearnLinks={OrderCloudLearnLinks}
            PlaygroundLinks={OrderCloudPlaygroundLinks}
          />          
          <ProductCard
            productName="Sitecore Commerce"
            productLink=""
            DocLinks={SitecoreCommerceDocLinks}
            DiscoverLinks={SitecoreCommerceDiscoverLinks}
            LearnLinks={SitecoreCommerceLearnLinks}
            PlaygroundLinks={SitecoreCommercePlaygroundLinks}
          />
          <div className={styles.socialsCard}>
            <h2>News & Announcements</h2>
            <a href="" className={styles.link}><li>Cool new commerce things</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Get Help</h2>
            <a href="https://support.sitecore.com/kb?id=kb_home" className={styles.link}><li>Sitecore Support</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Commerce Socials</h2>
            <a href="https://sitecore.stackexchange.com/?tags=sitecore-commerce" className={styles.link}><li>Sitecore Commerce Stack Exchange Tag</li></a>
            <a href="https://twitter.com/search?q=%23sitecorecommerce&src=typed_query&f=live" className={styles.link}><li>#SitecoreCommerce latest Tweets</li></a>
            <a href="https://twitter.com/Four51ecommerce" className={styles.link}><li>Four51 Twitter</li></a>
            <a href="https://twitter.com/search?q=%23ordercloud&src=typed_query&f=live" className={styles.link}><li>#OrderCloud latest Tweets</li></a>
          </div>
        </div>
      </main>

      <Footer />

    </div>)
}
function SitecoreCommerceLinks() {
  const SitecoreCommerceDocLinks = [
    { text: "Sitecore Commerce Documentation", url: "https://doc.sitecore.com/en/developers/101/xc/" }
  ]
  const SitecoreCommerceDiscoverLinks = [
    { text: "Knowledge Base", url: "" }
  ]
  const SitecoreCommerceLearnLinks = [
    { text: "YouTube: Sitecore Experience Commerce Deep Dive", url: "https://www.youtube.com/watch?v=T0cn3yBbRro&list=PL1jJVFm_lGny-vqNPTv3VdBA_o31-Tq94" },
    { text: "Getting Started", url: "https://doc.sitecore.com/en/developers/92/sitecore-experience-commerce/getting-started-with-development.html" }
  ]
  const SitecoreCommercePlaygroundLinks = [
    { text: "Downloads", url: "https://dev.sitecore.net/Downloads/Sitecore_Commerce.aspx" }
  ]
  return { SitecoreCommerceDocLinks, SitecoreCommerceDiscoverLinks, SitecoreCommerceLearnLinks, SitecoreCommercePlaygroundLinks }
}

function OrderCloudLinks() {
  const OrderCloudDocLinks = [
    { text: "Four51 Documentation", url: "https://four51.github.io/#/api" }
  ]
  const OrderCloudDiscoverLinks = [
    { text: "Ordercloud Feature Guide", url: "https://www.sitecore.com/resources/index/guide/ordercloud-feature-guide" }
  ]
  const OrderCloudLearnLinks = [
    { text: "Getting Started with OrderCloud", url: "https://ordercloud.io/getting-started/intro-to-ordercloud" }
  ]
  const OrderCloudPlaygroundLinks = [
    { text: "The Code 👩‍💻", url: "https://github.com/ordercloud-api" }
  ]
  return { OrderCloudDocLinks, OrderCloudDiscoverLinks, OrderCloudLearnLinks, OrderCloudPlaygroundLinks }
}

