import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Footer from '../../components/footer'
import { getMarkdownData } from "../../lib/getMarkdownData";
import ReactMarkdown from "react-markdown";

export async function getStaticProps() {
  const orderCloudData = await getMarkdownData("orderCloud.md");
  const sitecoreCommerceData = await getMarkdownData("sitecoreCommerce.md");

  return {
    props: {
      orderCloudData,
      sitecoreCommerceData
    },
  };
}

export default function Commerce({ orderCloudData, sitecoreCommerceData }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Commerce 💸
        </h1>
        <a href="/" className={styles.link}><h2>Take me Home</h2></a>
        <div className={styles.grid}>
          <div className={styles.searchCard}>
            <h2>I'm a unified search 🔍</h2>
          </div>


          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{orderCloudData.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{sitecoreCommerceData.markdown}</ReactMarkdown>
          </div>

          
          <div className={styles.socialsCard}>
            <h2>News & Announcements</h2>
            <a href="" className={styles.link}><li>Cool new commerce things</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Get Help</h2>
            <a href="https://support.sitecore.com/kb?id=kb_home" className={styles.link}><li>Sitecore Support</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Commerce Socials</h2>
            <a href="https://sitecore.stackexchange.com/?tags=sitecore-commerce" className={styles.link}><li>Sitecore Commerce Stack Exchange Tag</li></a>
            <a href="https://twitter.com/search?q=%23sitecorecommerce&src=typed_query&f=live" className={styles.link}><li>#SitecoreCommerce latest Tweets</li></a>
            <a href="https://twitter.com/Four51ecommerce" className={styles.link}><li>Four51 Twitter</li></a>
            <a href="https://twitter.com/search?q=%23ordercloud&src=typed_query&f=live" className={styles.link}><li>#OrderCloud latest Tweets</li></a>
          </div>
        </div>
      </main>

      <Footer />

    </div>)
}

