import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Commerce() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Commerce 💸
        </h1>
        <a href="/" className={styles.link}><h2>Take me Home</h2></a>
        <div className={styles.grid}>
          <div className={styles.searchCard}>
            <h2>I'm a unified search 🔍</h2>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="" ><h2>Four51 (OrderCloud)&rarr;</h2></a>
            <div className={styles.productSection}>
              Docs
              <a href="https://four51.github.io/#/api" className={styles.link}><li>Four51 Documentation</li></a>
            </div>
            <div className={styles.productSection}>
              Discover
              <a href="https://www.sitecore.com/resources/index/guide/ordercloud-feature-guide" className={styles.link}><li>Ordercloud Feature Guide</li></a>
            </div>
            <div className={styles.productSection}>
              Learn
              <a href="https://ordercloud.io/getting-started/intro-to-ordercloud" className={styles.link}><li>Getting Started</li></a>
            </div>
            <div className={styles.productSection}>
              Playground
              <a href="https://github.com/ordercloud-api" className={styles.link}><li>The Code 👩‍💻</li></a>
            </div>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="" ><h2>Sitecore Commerce&rarr;</h2></a>
            <div className={styles.productSection}>
              Docs
              <a href="https://doc.sitecore.com/en/developers/101/xc/" className={styles.link}><li>Sitecore Commerce Documentation</li></a>
            </div>
            <div className={styles.productSection}>
              Discover
              <a href="" className={styles.link}><li>Knowledge Base</li></a>
            </div>
            <div className={styles.productSection}>
              Learn
              <a href="https://www.youtube.com/watch?v=T0cn3yBbRro&list=PL1jJVFm_lGny-vqNPTv3VdBA_o31-Tq94" className={styles.link}><li>YouTube: Sitecore Experience Commerce Deep Dive</li></a>
              <a href="" className={styles.link}><li>Getting Started</li></a>
            </div>
            <div className={styles.productSection}>
              Playground
              <a href="https://dev.sitecore.net/Downloads/Sitecore_Commerce.aspx" className={styles.link}><li>Downloads</li></a>
            </div>
          </div>
          <div className={styles.socialsCard}>
            <h2>News & Announcements</h2>
            <a href="" className={styles.link}><li>Cool new commerce things</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Get Help</h2>
            <a href="https://support.sitecore.com/kb?id=kb_home" className={styles.link}><li>Sitecore Support</li></a>
          </div>
          <div className={styles.socialsCard}>
            <h2>Commerce Socials</h2>
            <a href="https://sitecore.stackexchange.com/?tags=sitecore-commerce" className={styles.link}><li>Sitecore Commerce Stack Exchange Tag</li></a>
            <a href="https://twitter.com/search?q=%23sitecorecommerce&src=typed_query&f=live" className={styles.link}><li>#SitecoreCommerce latest Tweets</li></a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>)
}
