import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Footer from '../../components/footer'
import { getMarkdownData } from "../../lib/getMarkdownData";
import ReactMarkdown from "react-markdown";

export async function getStaticProps() {
    const jssData = await getMarkdownData("jss.md");
    const sitecoreCDPData = await getMarkdownData("sitecoreCDP.md");
    const federatedExperienceManagerData = await getMarkdownData("federatedExperienceManager.md");
    const universalTracker = await getMarkdownData("universalTracker.md");

    return {
        props: {
            jssData,
            sitecoreCDPData,
            federatedExperienceManagerData,
            universalTracker
        },
    };
}

export default function Personalization({ jssData, sitecoreCDPData, federatedExperienceManagerData, universalTracker }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Personalization</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Personalization 🕵️‍♀️
                </h1>
                <a href="/" className={styles.link}><h2>Take me Home</h2></a>
                <div className={styles.grid}>
                    <div className={styles.searchCard}>
                        <h2>I'm a unified search 🔍</h2>
                    </div>



                    <div className={styles.productCategoryCard}>
                        <ReactMarkdown>{sitecoreCDPData.markdown}</ReactMarkdown>
                    </div>
                    <div className={styles.productCategoryCard}>
                        <ReactMarkdown>{jssData.markdown}</ReactMarkdown>
                    </div>
                    <div className={styles.productCategoryCard}>
                        <ReactMarkdown>{federatedExperienceManagerData.markdown}</ReactMarkdown>
                    </div>
                    <div className={styles.productCategoryCard}>
                        <ReactMarkdown>{universalTracker.markdown}</ReactMarkdown>
                    </div>



                    <div className={styles.socialsCard}>
                        <h2>News & Announcements</h2>
                        <a href="" className={styles.link}><li>Cool new personalization things</li></a>
                    </div>
                    <div className={styles.socialsCard}>
                        <h2>Get Help</h2>
                        <a href="https://support.sitecore.com/kb?id=kb_home" className={styles.link}><li>Sitecore Support</li></a>
                    </div>
                    <div className={styles.socialsCard}>
                        <h2>Commerce Socials</h2>
                        <a href="https://sitecore.stackexchange.com/?tags=jss" className={styles.link}><li>JSS Stack Exchange Tag</li></a>
                        <a href="https://sitecore.stackexchange.com/questions/tagged/personalization" className={styles.link}><li>Personalization Stack Exchange Tag</li></a>
                        <a href="https://twitter.com/search?q=sitecorejss&src=typed_query&f=live" className={styles.link}><li>#SitecoreJSS latest Tweets</li></a>
                        <a href="https://twitter.com/boxever" className={styles.link}><li>Boxever Twitter</li></a>
                    </div>
                </div>
            </main>
            <Footer />
        </div >
    )
}