import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { getMarkdownData } from "../../lib/getMarkdownData";
import ReactMarkdown from "react-markdown";

export async function getStaticProps() {
  const webTracking = await getMarkdownData("webTracking.md", "product");
  const sitecoreCDPData = await getMarkdownData("customer-data-management.md", "product/cdp");
  const xConnect = await getMarkdownData("xConnect.md", "product");
  const xDB = await getMarkdownData("xDB.md", "product");
  const referenceDataService = await getMarkdownData("referenceDataService.md", "product");

  return {
    props: {
        webTracking,
        sitecoreCDPData,
        xConnect,
        xDB,
        referenceDataService
    },
  };
}

export default function SitecoreCDP({ webTracking, sitecoreCDPData, xConnect, xDB, referenceDataService }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Sitecore CDP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Sitecore CDP 👨‍👨‍👧‍👧
        </h1>
        <div className={styles.grid}>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{webTracking.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{sitecoreCDPData.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{xConnect.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{xDB.markdown}</ReactMarkdown>
          </div>
          <div className={styles.productCategoryCard}>
            <ReactMarkdown>{referenceDataService.markdown}</ReactMarkdown>
          </div>


          <div className={styles.socialsCard}>
            <h2>General SitecoreCDP Socials</h2>
          </div> 
          <div className={styles.socialsCard}>
            <h2>News & Announcements</h2>
            <a href="" className={styles.link}><li>Cool new SitecoreCDP things</li></a>
          </div>
        </div>
      </main>
    </div>)
}

