import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dev Portal Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          🚧 Welcome to Dev Portal Demo 🚧
        </h1>

        <div className={styles.grid}>
          <div className={styles.searchCard}>
            <h2>I'm a unified search 🔍</h2>
          </div>
          {/* PRODUCT CATEGORIES */}
          <div className={styles.productCategoryCard}>
            <a href="products/commerce" ><h2>Commerce 💸 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Commerce</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/personalization" ><h2>Personalization 🕵️‍♀️ &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Personalization</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/sitecoreCDP" ><h2>Sitecore CDP 👨‍👨‍👧‍👧 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with CDP</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/marketingAutomation" ><h2>Marketing Automation 🚗 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Marketing Automation</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/webCMS" ><h2>Web CMS 💾 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Web CMS</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/headlessCMS" ><h2>Headless CMS 💻 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Headless CMS</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/DAM" ><h2>DAM 📀 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with DAM</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.youtubeCard}>
            <h2>I'm recent YouTube videos 🎥</h2>
          </div>
          <div className={styles.youtubeCard}>
            <h2>Join these cool Sitecore Communities 🤖</h2>
            <a href="https://sitecorechat.slack.com/" className={styles.link}><li>Slack</li></a>
            <a href="https://sitecore.stackexchange.com/" className={styles.link}><li>Stack Exchange</li></a>

          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
