import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Dev Portal Demo
        </h1>

        What do we NEED to have a minimum viable dev portal

        <div className={styles.grid}>
          {/* PRODUCTS */}
          <div className={styles.card}>
            <a href="https://www.sitecore.com/products" ><h2>Products (where do these link? Marketing page ❓) &rarr;</h2></a>
            <a href="products/commerce" className={styles.link}><li>Commerce</li></a>
            <a href="products/personalization" className={styles.link}><li>Personalization</li></a>
            <a href="products/sitecoreCDP" className={styles.link}><li>Sitecore CDP</li></a>
            <a href="products/marketingautomation" className={styles.link}><li>Marketing Automation</li></a>
            <a href="products/webCMS" className={styles.link}><li>Web CMS</li></a>
            <a href="products/headlessCMS" className={styles.link}><li>Headless CMS</li></a>
            <a href="products/DAM" className={styles.link}><li>DAM</li></a>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
