import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dev Portal Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <div class={styles.container}>
          <b>Navigate by Solution</b>
          <ul>
            <li>Content Management
              <ul>
                <li><a href="/content-management/content-hub">Sitecore Content Hub</a></li>
                <li><a href="/content-management/experience-manager">Sitecore Experience Manager</a></li>
              </ul>
            </li>
            <li><a href="/digital-asset-management">Digital Asset Management</a></li>
            <li>Customer Data Management
              <ul>
                <li><a href="/customer-data-management/cdp">Sitecore CDP</a></li>
                <li><a href="/customer-data-management/experience-platform">Sitecore Experience Platform</a></li>
              </ul>
            </li>
            <li>Personalization and Testing
              <ul>
                <li><a href="personalization-testing/cdp">Sitecore CDP</a></li>
                <li><a href="personalization-testing/experience-platform">Sitecore Experience Platform</a></li>
              </ul>
            </li>
            <li>Marketing Automation
              <ul>
                <li><a href="">Moosend</a></li>
                <li><a href="">Sitecore Experience Platform</a></li>
              </ul>
            </li>
            <li>Commerce
              <ul>
                <li><a href="">OrderCloud</a></li>
                <li><a href="">Sitecore Experience Commerce</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <div class={styles.container}>
          <b>Navigate by Product</b>
          <ul>
            <li>Sitecore Content Hub
              <ul>
                <li><a href="/content-management/content-hub">Content Management</a></li>
                <li><a href="/digital-asset-management/">Digital Asset Management</a></li>
              </ul>
            </li>
            <li>Sitecore CDP
              <ul>
                <li><a href="/customer-data-management/cdp">Customer Data Management</a></li>
                <li><a href="/personalization-testing/cdp">Personalization and Testing</a></li>
              </ul>
            </li>
            <li>Sitecore Experience Manager
              <ul>
                <li><a href="/content-management/experience-manager">Content Management</a></li>
                <li><a href="">Headless</a></li>
              </ul>
            </li>
            <li>Sitecore Experience Platform
              <ul>
                <li><a href="">Marketing Automation</a></li>
                <li><a href="/customer-data-management/experience-platform">Customer Data Management</a></li>
                <li><a href="/personalization-testing/experience-platform">Personalization and Testing</a></li>
              </ul>
            </li>
            <li><a href="">Moosend</a></li>
            <li><a href="">Sitecore Experience Commerce</a></li>
            <li><a href="">Sitecore OrderCloud</a></li>
          </ul>
        </div>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          🚧 Welcome to Dev Portal Demo 🚧
        </h1>

        <div className={styles.grid}>
          <div className={styles.searchCard}>
            <h2>I'm a unified search 🔍</h2>
          </div>
          {/* PRODUCT CATEGORIES */}
          <div className={styles.productCategoryCard}>
            <a href="products/commerce" ><h2>Commerce 💸 &rarr;</h2></a>
            <a href="products/commerce" className={styles.link}><li>Getting started with Commerce</li></a>
            <a href="https://four51.github.io/#/api" className={styles.link}><li>Four51 Documentation</li></a>
            <a href="https://doc.sitecore.com/en/developers/101/xc/" className={styles.link}><li>Sitecore Commerce Documentation</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/personalization" ><h2>Personalization 🕵️‍♀️ &rarr;</h2></a>
            <a href="products/personalization" className={styles.link}><li>Getting started with Personalization</li></a>
            <a href="" className={styles.link}><li>Boxever Documentation</li></a>
            <a href="" className={styles.link}><li>Sitecore XP Documentation</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/sitecoreCDP" ><h2>Sitecore CDP 👨‍👨‍👧‍👧 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with CDP</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/marketingautomation" ><h2>Marketing Automation 🚗 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Marketing Automation</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/marketingAutomation2" ><h2>Marketing Automation #2 🚗 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Marketing Automation</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/webCMS" ><h2>Web CMS 💾 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Web CMS</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/headlessCMS" ><h2>Headless CMS 💻 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with Headless CMS</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.productCategoryCard}>
            <a href="products/DAM" ><h2>DAM 📀 &rarr;</h2></a>
            <a href="" className={styles.link}><li>Getting started with DAM</li></a>
            <a href="" className={styles.link}><li>Docs</li></a>
          </div>
          <div className={styles.youtubeCard}>
            <h2>I'm recent YouTube videos 🎥</h2>
          </div>
          <div className={styles.youtubeCard}>
            <h2>Join these cool Sitecore Communities 🤖</h2>
            <a href="https://sitecorechat.slack.com/" className={styles.link}><li>Slack</li></a>
            <a href="https://sitecore.stackexchange.com/" className={styles.link}><li>Stack Exchange</li></a>
            <a href="https://www.sitecore.com/knowledge-center/blog" className={styles.link}><li>Sitecore Blog</li></a>
          </div>
          <div className={styles.youtubeCard}>
            <h2>Upcoming Events</h2>
          </div>
          <div className={styles.youtubeCard}>
            <h2>Help and Feedback</h2>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
